// frontend/src/components/TeamView.jsx
import { useState, useEffect, useCallback } from 'react';
import { useUser } from '../context/UserContext';
import api from '../api/axios';

export default function TeamView() {
  const { userId } = useUser();
  const [captures, setCaptures] = useState([]);
  const [team, setTeam] = useState([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const fetchData = useCallback(async () => {
    if (!userId) return;
    setLoading(true);
    try {
      const [capRes, teamRes] = await Promise.all([
        api.get('/capturas', { params: { userId } }),
        api.get(`/equipos/${userId}`)
      ]);
      setCaptures(capRes.data);
      setTeam(teamRes.data.equipo || []);
    } catch (err) {
      console.error('Error al cargar datos', err);
    } finally {
      setLoading(false);
    }
  }, [userId]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const togglePokemon = (captureId) => {
    setTeam(prev => {
      if (prev.includes(captureId)) return prev.filter(id => id !== captureId);
      if (prev.length >= 6) return prev;
      return [...prev, captureId];
    });
  };

  const saveTeam = async () => {
    setSaving(true);
    try {
      await api.put(`/equipos/${userId}`, { pokemonIds: team });
      alert('¡Equipo guardado!');
    } catch (err) {
      alert('Error al guardar equipo');
    } finally {
      setSaving(false);
    }
  };

  const spriteUrl = (name, shiny) =>
    `https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/${shiny ? 'shiny' : 'regular'}/${name.toLowerCase()}.png`;

  if (loading) {
    return (
      <div className="bg-gb-case p-6 rounded-t-3xl rounded-br-[4rem] rounded-bl-3xl border-4 border-black w-full max-w-2xl">
        <p className="text-[10px] text-center text-gray-600">Cargando...</p>
      </div>
    );
  }

  const teamCaptures = captures.filter(c => team.includes(c.id));
  const available = captures.filter(c => !team.includes(c.id));

  return (
    <div className="bg-gb-case p-6 rounded-t-3xl rounded-br-[4rem] rounded-bl-3xl border-4 border-black w-full max-w-2xl">
      {/* Team Slots */}
      <h2 className="text-xs text-gray-700 mb-2">EQUIPO ({team.length}/6)</h2>
      <div className="flex gap-2 mb-6 justify-center">
        {Array.from({ length: 6 }).map((_, i) => {
          const cap = teamCaptures[i];
          return (
            <div
              key={i}
              className={`w-16 h-16 border-2 border-black flex items-center justify-center ${
                cap ? 'bg-gb-screen cursor-pointer' : 'bg-gray-300'
              }`}
              onClick={() => cap && togglePokemon(cap.id)}
            >
              {cap ? (
                <div className="flex flex-col items-center">
                  <img src={spriteUrl(cap.pokemonName, cap.isShiny)} alt={cap.pokemonName} className="w-10 h-10 object-contain image-rendering-pixelated" />
                  <span className="text-[6px] text-gb-screen-dark uppercase truncate w-full text-center">{cap.nickname || cap.pokemonName}</span>
                </div>
              ) : (
                <span className="text-[10px] text-gray-500">-</span>
              )}
            </div>
          );
        })}
      </div>

      <button
        onClick={saveTeam}
        disabled={saving}
        className="btn-gameboy text-xs py-2 w-full mb-6"
      >
        {saving ? 'GUARDANDO...' : 'GUARDAR EQUIPO'}
      </button>

      {/* Available Captures */}
      <h3 className="text-[10px] text-gray-600 mb-2">TUS POKÉMON DISPONIBLES</h3>
      {available.length === 0 ? (
        <p className="text-[10px] text-center text-gray-500 py-4">
          {captures.length === 0 ? 'No tienes Pokémon capturados' : 'Todos están en el equipo'}
        </p>
      ) : (
        <div className="grid grid-cols-4 sm:grid-cols-6 gap-2">
          {available.map((cap) => (
            <button
              key={cap.id}
              onClick={() => togglePokemon(cap.id)}
              className="bg-gb-screen p-1 border-2 border-black flex flex-col items-center hover:scale-105 transition-transform"
            >
              <img src={spriteUrl(cap.pokemonName, cap.isShiny)} alt={cap.pokemonName} className="w-8 h-8 object-contain image-rendering-pixelated" />
              <span className="text-[6px] text-gb-screen-dark uppercase truncate w-full text-center">
                {cap.nickname || cap.pokemonName}
              </span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// frontend/src/views/TeamView.vue
<template>
  <div class="team-page">
    <h1 class="page-title">MI EQUIPO</h1>

    <div class="team-layout">
      <div class="team-section card">
        <h2>Equipo Actual ({{ team.length }}/6)</h2>
        <div class="team-slots">
          <div v-for="(c, idx) in team" :key="c.id" class="team-slot filled">
            <img :src="c.sprite" :alt="c.pokemonName" @error="e => e.target.src = defaultSprite" />
            <span>{{ c.nickname || c.pokemonName }}</span>
            <span class="small">Lv.{{ c.level }}</span>
            <button class="btn btn-danger btn-sm" @click="removeFromTeam(c.id)">
              <X :size="10" />
            </button>
          </div>
          <div v-for="n in (6 - team.length)" :key="'empty'+n" class="team-slot empty">
            <span class="empty-label">Vacio</span>
          </div>
        </div>
        <button class="btn btn-primary" @click="saveTeam" :disabled="saving">
          Guardar Equipo
        </button>
        <div class="endpoint-tag">GET /captures/team | PUT /captures/team</div>
      </div>

      <div class="available-section card">
        <h2>Tus Pokemon ({{ available.length }})</h2>
        <div class="available-grid" v-if="available.length">
          <div class="available-card" v-for="c in available" :key="c.id" @click="addToTeam(c)" :class="{ 'in-team': teamIds.includes(c.id) }">
            <img :src="c.sprite" :alt="c.pokemonName" @error="e => e.target.src = defaultSprite" />
            <span>{{ c.nickname || c.pokemonName }}</span>
            <span class="small">Lv.{{ c.level }}</span>
          </div>
        </div>
        <p v-else class="empty-text">No tienes Pokemon</p>
        <div class="endpoint-tag">GET /captures/my</div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { useToast } from '../composables/useToast';
import { X } from 'lucide-vue-next';
import api from '../api/axios';

const toast = useToast();
const team = ref([]);
const allCaptures = ref([]);
const saving = ref(false);
const defaultSprite = 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96"><rect fill="%23333" width="96" height="96" rx="8"/><text x="48" y="56" text-anchor="middle" fill="%23666" font-size="14">?</text></svg>';

const teamIds = computed(() => team.value.map(c => c.id));
const available = computed(() => allCaptures.value.filter(c => !teamIds.value.includes(c.id)));

onMounted(async () => {
  const [teamRes, allRes] = await Promise.all([
    api.get('/captures/team'),
    api.get('/captures/my')
  ]);
  team.value = teamRes.data;
  allCaptures.value = allRes.data;
});

function addToTeam(c) {
  if (teamIds.value.includes(c.id)) return;
  if (team.value.length >= 6) {
    toast.error('Equipo lleno. Quita uno primero.');
    return;
  }
  team.value.push(c);
}

function removeFromTeam(id) {
  team.value = team.value.filter(c => c.id !== id);
}

async function saveTeam() {
  saving.value = true;
  try {
    await api.put('/captures/team', { teamIds: teamIds.value });
    toast.success('Equipo actualizado');
  } catch (e) {
    toast.error(e.response?.data?.error || 'Error al guardar');
  } finally {
    saving.value = false;
  }
}
</script>

<style scoped>
.team-layout { display: flex; flex-direction: column; gap: 16px; }
.team-slots { display: grid; grid-template-columns: repeat(6, 1fr); gap: 8px; margin-bottom: 12px; }
.team-slot { background: rgba(0,0,0,0.2); border: 2px dashed rgba(255,255,255,0.1); border-radius: 8px; padding: 10px; text-align: center; display: flex; flex-direction: column; align-items: center; gap: 4px; min-height: 100px; }
.team-slot.filled { border-style: solid; border-color: var(--border); }
.team-slot img { width: 48px; height: 48px; image-rendering: pixelated; }
.team-slot span { font-size: 11px; }
.empty-label { color: var(--text-muted); font-size: 11px; }
.available-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(100px, 1fr)); gap: 8px; margin-top: 12px; }
.available-card { text-align: center; padding: 8px; border: 2px solid transparent; border-radius: 8px; cursor: pointer; transition: all 0.2s; }
.available-card:hover { border-color: var(--accent); background: rgba(254, 50, 51, 0.1); }
.available-card img { width: 48px; height: 48px; image-rendering: pixelated; }
.available-card span { font-size: 11px; display: block; }
</style>
